### ISSUE TITLE
creation of ECR registry?

### ISSUE THREAD

**Issue by danny-kirby** [aws-samples/cloud-gaming-on-ec2-instances#12]
Where in the code is the need for an ECR registry as well as filepublishingrole? ,
upon running the `cdk bootstrap --verbose` , I see on the output the following get generated

CDKToolkit |  0/12 | 10:48:20 AM | CREATE_IN_PROGRESS   | AWS::ECR::Repository    | ContainerAssetsRepository Resource creation Initiated
CDKToolkit |  1/12 | 10:48:20 AM | CREATE_COMPLETE      | AWS::SSM::Parameter     | CdkBootstrapVersion 
CDKToolkit |  2/12 | 10:48:20 AM | CREATE_COMPLETE      | AWS::ECR::Repository    | ContainerAssetsRepository 
[10:48:25] Stack CDKToolkit has an ongoing operation in progress and is not stable (CREATE_IN_PROGRESS)
[10:48:30] Stack CDKToolkit has an ongoing operation in progress and is not stable (CREATE_IN_PROGRESS)
CDKToolkit |  3/12 | 10:48:32 AM | CREATE_COMPLETE      | AWS::IAM::Role          | FilePublishingRole 
CDKToolkit |  4/12 | 10:48:33 AM | CREATE_COMPLETE      | AWS::IAM::Role          | CloudFormationExecutionRole 
CDKToolkit |  5/12 | 10:48:33 AM | CREATE_COMPLETE      | AWS::IAM::Role          | ImagePublishingRole 
CDKToolkit |  6/12 | 10:48:33 AM | CREATE_COMPLETE      | AWS::IAM::Role          | LookupRole

**Comment by Seblat5ch** [comment]
This is part of the CDK bootstrap minimum requirements and is used to deploy your assets. 

<html><body>


Feature | Legacy (v1 only) | Modern (v1 and v2)
-- | -- | --
Cross-account deployments | Not allowed | Allowed
AWS CloudFormation Permissions | Deploys using current user's permissions (determined by AWS profile,               environment variables, etc.) | Deploys using the permissions specified when the bootstrap stack was provisioned               (for example, by using --trust)
Versioning | Only one version of bootstrap stack is available | Bootstrap stack is versioned; new resources can be added in future versions, and               AWS CDK apps can require a minimum version
Resources* | Amazon S3 bucket | Amazon S3 bucket
|| |AWS KMS key
|| |IAM roles
|| |Amazon ECR repository
|| |SSM parameter for versioning
Resource naming | Automatically generated | Deterministic
Bucket encryption | Default key | Customer managed key


</body>
</html>

* We will add additional resources to the bootstrap template as needed.

https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-template
