### ISSUE TITLE
Install Drivers

### ISSUE THREAD

**Issue by ROX7** [aws-samples/cloud-gaming-on-ec2-instances#21]
The DriverInstallationFiles are different friom the tutorial, can you provide some explanation of what to do now that the files changed ? 
Also i try install directX on the instance but i got an error as soon as start the install with the error: unable to download file.
Directx is highly used by games, so i think its important to be able to install it ? 
Thanks for your help
i'm using G4DN.xlarge with windows server 2022

**Comment by markusz** [comment]
Hi @ROX7 

which instructions are you following? The ones in the README?

**Comment by ROX7** [comment]
I was following this :[ https://aws.amazon.com/fr/blogs/compute/use-amazon-ec2-for-cost-efficient-cloud-gaming-with-pay-as-you-go-pricing](tuto)
but at the end i had to install additional nvidia drivers, and the only way that worked was to download a game that install this drivers for me, in my case, I downloaded ubisoft connect, and after downloading far cry 4 on it, it installed all the drivers needed to run it.
that solved the drivers issues of my other games.

**Comment by markusz** [comment]
Thanks ROX7, we'll work on getting the blogpost updated with new instructions. The project README should refelct those already
