### ISSUE TITLE
Installation feedback and issues

### ISSUE THREAD

**Issue by drewmullen** [aws-samples/cloud-gaming-on-ec2-instances#7]
Hi, thanks for putting this together. A few points from my installation exp building `CloudGamingOnG4DN`

1. the nvidia drivers did not download to the dir. i had to installing using [these instructions](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver.html)
2. i have NICE dcv running on my laptop, connected to my machine but i cannot get resolution past 1080p. looks a little ridiculous - researching now how to fix it but wanted to report these to yall

thanks again
<img width="1920" alt="Screenshot 2023-01-07 154638" src="https://user-images.githubusercontent.com/3812162/211169744-52c318fa-45a9-433f-9760-73e52865d15f.png">

**Comment by drewmullen** [comment]
after a bit i couldnt get nice dcv to resize appropriately, i think it has something to do with the drivers. switched to AD instance type 

the AD install worked fine. took me a little while to figure out the last pwsh command in the driver installation - thought "install" was a file that i couldnt find 😅 but nice dcv is working great with it. shutting down the dn server

**Comment by ROX7** [comment]
> Hi, thanks for putting this together. A few points from my installation exp building `CloudGamingOnG4DN`
> 
> 1. the nvidia drivers did not download to the dir. i had to installing using [these instructions](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver.html)
> 2. i have NICE dcv running on my laptop, connected to my machine but i cannot get resolution past 1080p. looks a little ridiculous - researching now how to fix it but wanted to report these to yall
> 
> thanks again <img alt="Screenshot 2023-01-07 154638" width="1920" src="https://user-images.githubusercontent.com/3812162/211169744-52c318fa-45a9-433f-9760-73e52865d15f.png">

Did you install directx ? Yes : how ? No : why?
